<div class="mycontent">
  <div class="myposttitle">

  </div>
  <div class="mypostcontent">
    <p>I moved to the UK in 2007. I worked in wholesale sector for 8 years. During that time I decided to change my career and become a software developer. I am currently studying part-time at the Open University towards the degree in Computing & IT and Statistics. I look forward to learning new skills in professional environment and beginning my new career path.<p>
  </div>
</div>
