<header class="myheader">
  <nav class="mynavbar">
    <div class="mymenu">
      <!--Use different styles for current menu item-->
      <div class="mymenuitem"><a href="index.php">Home</a></div>
      <div class="mymenuitem"><a href="index.php?pagetitle=about">About</a></div>
      <div class="mymenuitem"><a href="index.php?pagetitle=usefullinks">Useful links</a></div>
      <div class="mymenuitem"><a href="index.php?pagetitle=contact">Contact</a></div>
    </div>
  </nav>

    <?php
      echo $mytitlediv;
    ?>

</header>
