  <div class="mycontent">
    <div class="myposttitle">
      About Scrum
    </div>
    <div class="mypostcontent">
      <ul class="list">
        <li><a href="http://www.scrumprimer.org/scrumprimer20_small.pdf">The Scrum Primer</li>
        <li><a href="http://www.agilelearninglabs.com/resources/scrum-introduction/">Scrum: A Breathtakingly Brief and Agile Introduction</a></li>
        <li><a href="https://www.youtube.com/watch?v=D8vT7G0WATM">Introduction to Scrum - CollabNet Scrum Training Part 1</a></li>
      </ul>
    </div>
  </div>
